apiVersion: v1
kind: Pod
spec:
  imagePullSecrets:
  - name: jenkins-harbor
  containers:
  - name: busybox
    image: busybox:latest
    command: ['cat']
    tty: true
  - name: git
    image: alpine/git:latest
    command: ['cat']
    tty: true
  - name: helm
    image: core.c7d.net/c7d/utility-helm:v3.3.4
    command: ['cat']
    tty: true
  - name: golang
    image: golang:1.16.3-buster
    command: ['cat']
    tty: true
  - name: kaniko
    image: gcr.io/kaniko-project/executor:debug
    command: ['cat']
    tty: true
    volumeMounts:
      - name: jenkins-docker-config-volume
        mountPath: /kaniko/.docker
  volumes:
  - name: jenkins-docker-config-volume
    secret:
      secretName: jenkins-harbor
      items:
      - key: .dockerconfigjson
        path: config.json
