apiVersion: v1
kind: Pod
spec:
  imagePullSecrets:
  - name: jenkins-harbor
  containers:
  - name: busybox
    image: busybox:latest
    command: ['cat']
    tty: true
  - name: git
    image: alpine/git:latest
    command: ['cat']
    tty: true
  - name: helm
    image: core.c7d.net/c7d/utility-helm:v3.3.4
    command: ['cat']
    tty: true
